POST  http://localhost:3000/api/auth/signup
Content-Type:application/json

{
    "email":"t.hilbert@wanadoo.fr",
    "password":"1234"
}
###
POST  http://localhost:3000/api/auth/login
Content-Type:application/json

{
    "email":"a",
    "password":"b"
}
###
POST  http://localhost:3000/api/sauces

{
    "userId":"frank",
    "name":"tabasco",
    "manufacturer":"kraft",
    "description": "bouteille",
    "mainPepper":"poivre",
    "imageUrl":"",
    "heat":"",
    "likes":0,
    "dislikes":0,
    "usersLiked":"",
    "usersDisliked":""
}
###
GET http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTAwMGIzNDZjOGI0YWU1N2IzNGNjNTQiLCJpYXQiOjE2Mjc2MDE3NTEsImV4cCI6MTYyNzY4ODE1MX0.yAJkzYG-CyHR-UQK3vF2yXFFqUij5VQ2X2o6lcQl9GY
###
# db.sauces.insert({
#         "userId":"frank",
#     "name":"tabasco",
#     "manufacturer":"kraft",
#     "description": "bouteille",
#     "mainPepper":"poivre",
#     "imageUrl":"",
#     "heat":8,
#     "likes":3,
#     "dislikes":2,
#     "usersLiked":"",
#     "usersDisliked":""
# })
# db.sauces.update({userId:"frank"},
#     {$set: {
#             likes:5

#     } })
#     "name":"tabasco",
#     "manufacturer":"kraft",
#     "description": "bouteille",
#     "mainPepper":"poivre",
#     "imageUrl":"",
#     "heat":8,
#     "likes":3,
#     "dislikes":2,
#     "usersLiked":"",
#     "usersDisliked":""
# })

